[project]
name = "ai-video-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Khushbu Rawat", email = "khushburawat541@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.5.9",
    "deep-translator>=1.11.4",
    "ffmpeg-python>=0.2.0",
    "fpdf2>=2.8.8",
    "huggingface-hub>=1.32.0",
    "langchain>=1.4.1",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-huggingface>=1.2.2",
    "langchain-mistralai>=1.1.6",
    "mistralai>=2.10.1",
    "onnxruntime<1.24",
    "openai-whisper>=20250625",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "reportlab>=5.0.1",
    "sentence-transformers>=6.1.0",
    "streamlit>=1.64.0",
    "streamlit-extras>=1.6.0",
    "torchvision>=0.29.0",
    "watchdog>=6.0.0",
    "yt-dlp[default]>=2026.8.19",
]

[project.scripts]
ai-video-assistant = "ai_video_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
