[project]
name = "ai-video-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Khushbu Rawat", email = "khushburawat541@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "openai-whisper>=20250625",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
ai-video-assistant = "ai_video_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
